import React, { useState, useEffect, useRef } from 'react';
import { MessageCircle, X, Send, Bot, User, Minimize2, Maximize2, Clock, BookOpen, TrendingUp, Play } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { useCourses } from '../contexts/CourseContext';
import chatService from '../services/chatService';

interface Course {
  title: string;
  instructor: string;
  duration: string;
  level: string;
  price?: string;
  rating?: number;
  description?: string;
}

interface Message {
  id: string;
  text: string;
  isBot: boolean;
  timestamp: Date;
  videos?: VideoRecommendation[];
  courseContent?: CourseContent;
  aiPowered?: boolean; // Indicates if the response was generated by AI
  type?: string; // Message type (text, questionnaire, recommendation, etc.)
  courses?: Course[];
  videoUrl?: string; // Single video URL for direct embedding
}

interface VideoRecommendation {
  title: string;
  url: string;
  duration: string;
  description: string;
  technology: string;
}

interface CourseContent {
  title: string;
  structure: {
    section: string;
    topics: string[];
  }[];
  estimatedTime: string;
  difficulty: string;
}

interface QuickAction {
  id: string;
  label: string;
  icon: React.ReactNode;
  action: string;
}

const ChatBot: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [isMinimized, setIsMinimized] = useState(false);
  const [messages, setMessages] = useState<Message[]>([]);
  const [inputText, setInputText] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const { user } = useAuth();
  const { courses: _courses } = useCourses();

  const quickActions: QuickAction[] = [
    {
      id: 'start-questionnaire',
      label: 'Learning Path Guide',
      icon: <User className='w-4 h-4' />,
      action: 'I want to start learning programming, can you help me?'
    },
    {
      id: 'recommend-courses',
      label: 'Recommend Courses',
      icon: <BookOpen className='w-4 h-4' />,
      action: 'Can you recommend some courses for me?'
    },
    {
      id: 'study-schedule',
      label: 'Study Schedule',
      icon: <Clock className='w-4 h-4' />,
      action: 'Help me create a study schedule'
    },
    {
      id: 'trending-topics',
      label: 'Trending Topics',
      icon: <TrendingUp className='w-4 h-4' />,
      action: 'What are the trending programming topics?'
    },
    {
      id: 'video-tutorials',
      label: 'Video Tutorials',
      icon: <Play className='w-4 h-4' />,
      action: 'Show me video tutorials for web development'
    }
  ];

  useEffect(() => {
    if (isOpen && messages.length === 0) {
      const welcomeMessage: Message = {
        id: '0',
        text: 'Hello' + (user ? ' there' : '') + '! 👋 I am your intelligent learning assistant. I can help you with:\n\n✨ **Personalized Learning Path** - Take our interactive questionnaire to get customized recommendations\n📚 **Course Recommendations** - Find the perfect courses for your goals\n📹 **Video Tutorials** - Watch curated videos directly in our chat\n📅 **Study Schedules** - Create optimized learning plans\n\nClick "Learning Path Guide" below to start your personalized journey!',
        isBot: true,
        timestamp: new Date()
      };
      setMessages([welcomeMessage]);
    }
  }, [isOpen, user]);

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const handleSendMessage = async (text: string) => {
    if (!text.trim()) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      text,
      isBot: false,
      timestamp: new Date()
    };

    setMessages(prev => [...prev, userMessage]);
    setInputText('');
    setIsLoading(true);

    try {
      const response = await chatService.sendMessage(text);
      
      // Handle different response formats
      let messageText = '';
      let messageType = 'text';
      let videos: VideoRecommendation[] = [];
      let courses: Course[] = [];
      let videoUrl = '';
      
      if (response.message?.text) {
        messageText = response.message.text; // Enhanced chat format
        messageType = response.message.type || 'text';
        videos = response.message.videos || [];
        courses = response.message.courses || [];
        videoUrl = response.message.videoUrl || '';
      } else if (response.message) {
        messageText = response.message; // Regular chat format
      } else if (response.response) {
        messageText = response.response; // Alternative format
      } else {
        messageText = 'I received your message but there was an issue with the response.';
      }
      
      const botMessage: Message = {
        id: (Date.now() + 1).toString(),
        text: messageText,
        isBot: true,
        timestamp: new Date(),
        type: messageType,
        videos: videos,
        courses: courses,
        videoUrl: videoUrl,
        courseContent: response.courseContent || response.message?.courseContent,
        aiPowered: response.aiPowered || false
      };

      setMessages(prev => [...prev, botMessage]);
    } catch (error) {
      console.error('Chat error:', error);
      const errorMessage: Message = {
        id: (Date.now() + 1).toString(),
        text: 'Sorry, I encountered an error. Please try again.',
        isBot: true,
        timestamp: new Date()
      };
      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleQuickAction = (action: string) => {
    handleSendMessage(action);
  };

  const handleVideoClick = (video: VideoRecommendation) => {
    if (video.url.includes('youtube.com') || video.url.includes('youtu.be')) {
      window.open(video.url, '_blank');
    } else {
      window.open(video.url, '_blank');
    }
  };

  const renderVideoEmbed = (videoUrl: string) => {
    // Convert YouTube URL to embed format
    let embedUrl = videoUrl;
    if (videoUrl.includes('youtube.com/watch?v=')) {
      const videoId = videoUrl.split('v=')[1]?.split('&')[0];
      embedUrl = `https://www.youtube.com/embed/${videoId}`;
    } else if (videoUrl.includes('youtu.be/')) {
      const videoId = videoUrl.split('youtu.be/')[1]?.split('?')[0];
      embedUrl = `https://www.youtube.com/embed/${videoId}`;
    }

    return (
      <div className='mt-3'>
        <h4 className='font-semibold text-sm text-gray-700 mb-2'>🎥 Watch this video:</h4>
        <div className='relative w-full h-48 bg-gray-100 rounded-lg overflow-hidden'>
          <iframe
            src={embedUrl}
            title="Learning Video"
            className='w-full h-full'
            frameBorder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen
          />
        </div>
        <p className='text-xs text-gray-600 mt-1'>
          <a href={videoUrl} target="_blank" rel="noopener noreferrer" className='text-blue-600 hover:underline'>
            Open in new tab ↗
          </a>
        </p>
      </div>
    );
  };

  const renderCourseRecommendations = (courses: Course[]) => (
    <div className='mt-3 space-y-3'>
      <h4 className='font-semibold text-sm text-gray-700'>🎓 Recommended Courses:</h4>
      {courses.map((course, index) => (
        <div key={index} className='bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg p-3'>
          <div className='flex items-start justify-between'>
            <div className='flex-1'>
              <h5 className='font-semibold text-sm text-gray-900'>{course.title}</h5>
              <p className='text-xs text-gray-600 mt-1'>by {course.instructor}</p>
              {course.description && (
                <p className='text-xs text-gray-700 mt-2 line-clamp-2'>{course.description}</p>
              )}
              <div className='flex items-center space-x-3 mt-2'>
                <span className='text-xs px-2 py-1 bg-blue-100 text-blue-700 rounded'>
                  {course.level}
                </span>
                <span className='text-xs text-gray-600'>{course.duration}</span>
                {course.rating && (
                  <span className='text-xs text-yellow-600'>⭐ {course.rating}</span>
                )}
              </div>
            </div>
            {course.price && (
              <div className='text-right'>
                <span className='text-sm font-semibold text-green-600'>{course.price}</span>
              </div>
            )}
          </div>
        </div>
      ))}
    </div>
  );

  const renderVideoPlaylist = (videos: VideoRecommendation[]) => (
    <div className='mt-3 space-y-2'>
      <h4 className='font-semibold text-sm text-gray-700'>📺 Video Recommendations:</h4>
      {videos.map((video, index) => (
        <div 
          key={index}
          className='bg-gray-50 rounded-lg p-3 cursor-pointer hover:bg-gray-100 transition-colors'
          onClick={() => handleVideoClick(video)}
        >
          <div className='flex items-start space-x-3'>
            <div className='flex-shrink-0 w-8 h-8 bg-red-100 rounded-full flex items-center justify-center'>
              <Play className='w-4 h-4 text-red-600' />
            </div>
            <div className='flex-1 min-w-0'>
              <h5 className='font-medium text-sm text-gray-900 truncate'>{video.title}</h5>
              <p className='text-xs text-gray-600 mt-1 line-clamp-2'>{video.description}</p>
              <div className='flex items-center justify-between mt-2'>
                <span className='text-xs px-2 py-1 bg-blue-100 text-blue-700 rounded'>
                  {video.technology}
                </span>
                <span className='text-xs text-gray-500'>{video.duration}</span>
              </div>
            </div>
          </div>
        </div>
      ))}
    </div>
  );

  const renderCourseContent = (courseContent: CourseContent) => (
    <div className='mt-3 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg p-4'>
      <div className='flex items-center space-x-2 mb-3'>
        <BookOpen className='w-5 h-5 text-blue-600' />
        <h4 className='font-semibold text-gray-800'>{courseContent.title}</h4>
      </div>
      
      <div className='grid grid-cols-2 gap-2 mb-3 text-xs'>
        <div className='bg-white/60 rounded px-2 py-1'>
          <span className='text-gray-600'>Duration: </span>
          <span className='font-medium'>{courseContent.estimatedTime}</span>
        </div>
        <div className='bg-white/60 rounded px-2 py-1'>
          <span className='text-gray-600'>Level: </span>
          <span className='font-medium'>{courseContent.difficulty}</span>
        </div>
      </div>

      <div className='space-y-2'>
        <h5 className='font-medium text-sm text-gray-700'>📚 Course Structure:</h5>
        {courseContent.structure.map((section, index) => (
          <div key={index} className='bg-white/60 rounded-lg p-2'>
            <h6 className='font-medium text-xs text-gray-800 mb-1'>{section.section}</h6>
            <ul className='text-xs text-gray-600 space-y-1'>
              {section.topics.map((topic, topicIndex) => (
                <li key={topicIndex} className='flex items-center space-x-1'>
                  <span className='w-1 h-1 bg-blue-400 rounded-full flex-shrink-0'></span>
                  <span>{topic}</span>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </div>
  );

  if (!isOpen) {
    return (
      <button
        onClick={() => setIsOpen(true)}
        className='fixed bottom-6 right-6 bg-blue-600 hover:bg-blue-700 text-white p-4 rounded-full shadow-lg transition-all duration-300 hover:scale-110 z-50'
      >
        <MessageCircle className='w-6 h-6' />
      </button>
    );
  }

  return (
    <div className={'fixed bottom-6 right-6 bg-white rounded-xl shadow-2xl border z-50 transition-all duration-300 ' + (isMinimized ? 'w-80 h-16' : 'w-96 h-[600px]')}>
      <div className='flex items-center justify-between p-4 border-b bg-gradient-to-r from-blue-600 to-indigo-600 text-white rounded-t-xl'>
        <div className='flex items-center space-x-2'>
          <Bot className='w-5 h-5' />
          <span className='font-semibold'>Learning Assistant</span>
        </div>
        <div className='flex items-center space-x-2'>
          <button
            onClick={() => setIsMinimized(!isMinimized)}
            className='p-1 hover:bg-white/20 rounded transition-colors'
          >
            {isMinimized ? <Maximize2 className='w-4 h-4' /> : <Minimize2 className='w-4 h-4' />}
          </button>
          <button
            onClick={() => setIsOpen(false)}
            className='p-1 hover:bg-white/20 rounded transition-colors'
          >
            <X className='w-4 h-4' />
          </button>
        </div>
      </div>

      {!isMinimized && (
        <>
          <div className='flex-1 p-4 h-96 overflow-y-auto space-y-4'>
            {messages.map((message) => (
              <div
                key={message.id}
                className={'flex ' + (message.isBot ? 'justify-start' : 'justify-end')}
              >
                <div className={'max-w-[80%] ' + (message.isBot ? 'bg-gray-100' : 'bg-blue-600 text-white') + ' rounded-lg p-3'}>
                  <div className='flex items-start space-x-2'>
                    {message.isBot && <Bot className='w-4 h-4 mt-0.5 text-blue-600' />}
                    <div className='flex-1'>
                      <p className='text-sm whitespace-pre-wrap'>{message.text}</p>
                      {message.videoUrl && renderVideoEmbed(message.videoUrl)}
                      {message.videos && message.videos.length > 0 && renderVideoPlaylist(message.videos)}
                      {message.courses && message.courses.length > 0 && renderCourseRecommendations(message.courses)}
                      {message.courseContent && renderCourseContent(message.courseContent)}
                    </div>
                    {!message.isBot && <User className='w-4 h-4 mt-0.5' />}
                  </div>
                  <span className='text-xs opacity-70 mt-1 block'>
                    {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </span>
                </div>
              </div>
            ))}
            {isLoading && (
              <div className='flex justify-start'>
                <div className='bg-gray-100 rounded-lg p-3 max-w-[80%]'>
                  <div className='flex items-center space-x-2'>
                    <Bot className='w-4 h-4 text-blue-600' />
                    <div className='flex space-x-1'>
                      <div className='w-2 h-2 bg-gray-400 rounded-full animate-bounce'></div>
                      <div className='w-2 h-2 bg-gray-400 rounded-full animate-bounce' style={{ animationDelay: '0.1s' }}></div>
                      <div className='w-2 h-2 bg-gray-400 rounded-full animate-bounce' style={{ animationDelay: '0.2s' }}></div>
                    </div>
                  </div>
                </div>
              </div>
            )}
            <div ref={messagesEndRef} />
          </div>

          <div className='px-4 py-2 border-t bg-gray-50'>
            <div className='flex flex-wrap gap-2'>
              {quickActions.map((action) => (
                <button
                  key={action.id}
                  onClick={() => handleQuickAction(action.action)}
                  className='flex items-center space-x-1 px-2 py-1 bg-white hover:bg-gray-100 text-gray-700 text-xs rounded-full border transition-colors'
                  disabled={isLoading}
                >
                  {action.icon}
                  <span>{action.label}</span>
                </button>
              ))}
            </div>
          </div>

          <div className='p-4 border-t'>
            <div className='flex space-x-2'>
              <input
                type='text'
                value={inputText}
                onChange={(e) => setInputText(e.target.value)}
                onKeyPress={(e) => e.key === 'Enter' && !isLoading && handleSendMessage(inputText)}
                placeholder='Ask me anything about learning...'
                className='flex-1 px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 text-sm'
                disabled={isLoading}
              />
              <button
                onClick={() => handleSendMessage(inputText)}
                disabled={isLoading || !inputText.trim()}
                className='px-4 py-2 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 text-white rounded-lg transition-colors'
              >
                <Send className='w-4 h-4' />
              </button>
            </div>
          </div>
        </>
      )}
    </div>
  );
};

export default ChatBot;
